# Generated by Django 2.0 on 2018-10-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='gare_arrivee',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='gare_depart',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='heure_depart',
        ),
        migrations.AddField(
            model_name='train',
            name='gare_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_arrivee', to='network.Gare'),
        ),
        migrations.AddField(
            model_name='train',
            name='gare_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_depart', to='network.Gare'),
        ),
        migrations.AddField(
            model_name='train',
            name='heure_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='heure_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
