# Generated by Django 2.0 on 2018-10-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20181020_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='heure_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='heure_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
