# Generated by Django 2.0 on 2018-10-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20181021_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
