# Generated by Django 2.0 on 2018-10-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_place_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billet',
            name='reduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.Reduction'),
        ),
    ]
