# Generated by Django 2.0 on 2018-10-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20181022_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='GareArret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('heure', models.DateTimeField(blank=True, null=True)),
                ('gare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.Gare')),
            ],
            options={
                'db_table': 'gare_arret',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ville',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='train',
            name='gare_arrivee',
        ),
        migrations.RemoveField(
            model_name='train',
            name='gare_depart',
        ),
        migrations.RemoveField(
            model_name='train',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='train',
            name='heure_depart',
        ),
        migrations.RemoveField(
            model_name='train',
            name='prix_brut',
        ),
        migrations.AddField(
            model_name='billet',
            name='gare_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_arrivee', to='network.Gare'),
        ),
        migrations.AddField(
            model_name='billet',
            name='gare_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_depart', to='network.Gare'),
        ),
        migrations.AddField(
            model_name='billet',
            name='heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billet',
            name='heure_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garearret',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.Train'),
        ),
        migrations.AddField(
            model_name='gare',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.Ville'),
        ),
    ]
