# Generated by Django 2.0 on 2018-10-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20181022_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='heure_depart',
        ),
        migrations.AlterField(
            model_name='billet',
            name='gare_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_arrivee', to='network.GareArret'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='gare_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gare_depart', to='network.GareArret'),
        ),
    ]
