# Generated by Django 2.0 on 2018-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20181022_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, max_length=200, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
